package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, December 18, 2013 6:35:31 PM PST
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
	 */
  public static final int value = (int)(20L);
}
